### PR TITLE
migrate to open-easycrt to fix WebRTC bugs and about 300 knows vulnerabilities

### PR DESCRIPTION
**Pull request by hthetiot**
This PR simply migrate from 3 years old easyrtc to latest open-easyrtc.

OpenEasyRTC ChangeLogs: https://github.com/open-easyrtc/open-easyrtc/blob/master/docs/easyrtc_changelog.md#easyrtc-change-log
Full EasyRTC to OpenEasyRTC ChangeLogs: https://github.com/open-easyrtc/open-easyrtc/issues/6

Before: found 487 vulnerabilities (164 low, 25 moderate, 295 high, 3 critical)
After: found 82 vulnerabilities (30 low, 22 moderate, 30 high) in 9024 scanned packages

npm audit from open-easyrtc package itself currentlty result in: found 5 vulnerabilities (1 moderate, 4 high)

### CODE REVIEW

**Comment by hthetiot** [comment]
Quick test result confirm no regression.
Screen Shot 2019-12-06 at 1 21 48 PM

**Comment by haydenjameslee** [comment]
I'll be merging a native webrtc adapter soon: https://github.com/networked-aframe/networked-aframe/pull/176 instead of using easyrtc or open-easyrtc. I appreciate the heads up on easyrtc though and I'll make a separate repo for an open-easyrtc adapter.

**Comment by hthetiot** [comment]
I think this could have been a minor version increment that fix more than 300 security issues.
But that your call and your users.

**Comment by haydenjameslee** [comment]
Yeah if I was more active with updates that would've been a good idea. I had optimistically thought I'd get the native-webrtc update out over the holidays and thus it wouldn't be worth shipping two updates within a small period of time.

**Pull request closed without merging**
