### PR TITLE
Update hosting-networked-aframe-on-a-server.md

### PR DESCRIPTION
**Pull request by dirkk0**
added code

refs #169

### CODE REVIEW

**Comment by vincentfretin** [comment]
Hi, sorry I'm not merging this right now. I don't think the instructions are enough for a complete beginner, you don't explain how to generate the certificate.

I'm curious, are you using tls termination on nodejs for production, exposing the nodejs port directly?
I know someone that do the tls termination on nodejs but expose nodejs behind IIS on Windows server.
I usually put nodejs behind nginx or traefik and do the tls termination on nginx or traefik.

In the getting started tutorial, there is "Using HTTPS locally:" https://github.com/networked-aframe/networked-aframe/blob/master/docs/getting-started-local.md#voice-chat--audio-streaming where we explain to use ngrok.
I think a good alternative is using your above code with a certificate generated with [mkcert](https://github.com/FiloSottile/mkcert) so to explain all that in the getting started tutorial.

For production deployment so in the https://github.com/networked-aframe/networked-aframe/blob/master/docs/hosting-networked-aframe-on-a-server.md document , we can reference those instructions again, but we should probably explain how to configure nginx #244

**Comment by dirkk0** [comment]
Hi Vincent, np at all!

I usually use Letsencrypt to create a real certificate, since I mainly use this on either an AWS instance or a Raspi for temporary installations. I don't have a production environment/use case atm, but I would also be interested on how to so a proper setup with nginx and the likes.

For an experimental environement using Letsencrypt seems easy enough, and I could document this, if you feel this is useful.

I can't comment much on mkcert but if this doesn't create a 'real' certificate it is useless for my scenarios.

**Comment by vincentfretin** [comment]
For a deployment with nginx, I usually use certbot to generate a letsencrypt certificate so yeah it would be good to document it.
For mkcert, it's not a real certificate for production, it's only for development. It's better than a self generated certificate generated with openssl command for example because it adds a CA to your system and create the certificate with this registered CA, so you don't have the warning about it not being secure.

**Comment by dirkk0** [comment]
ok, I see - so we have 4 possible levels:
- no certs
- certs with mkcert
- certs with letsencrypt
- production setup with nginx et al
which we should somehow document, right?

**Comment by vincentfretin** [comment]
yes

**Pull request closed without merging**
