### PR TITLE
Allow registering network adapters via the NAF global

### PR DESCRIPTION
**Pull request by robertlong**
Currently all network adapters are included in the networked-aframe library. Eventually it would make sense if all adapters were split out of the core networked-aframe library and into separate modules.

If you are including the easyrtc adapter via script tags it might look like this:
```
<script src="https://aframe.io/releases/0.7.0/aframe.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/1.4.5/socket.io.min.js"></script>
<script src="https://unpkg.com/networked-aframe/dist/networked-aframe.min.js"></script>
<script src="https://unpkg.com/networked-aframe/dist/networked-aframe-easyrtc-adapter.min.js"></script>
```

Inside each adapter you would call `NAF.adapters.register(adapterName, AdapterClass);`

So the easyrtc adapter would look like this:

```
class EasyRTCAdapter {
  // ...
}

NAF.adapters.register("easyrtc", EasyRTCAdapter);
```

Additionally this exposes an API for developers to create third party network adapters. The Mozilla MR team has been working on one that uses the Janus WebRTC server as a backend:
https://github.com/netpro2k/networked-aframe/blob/feature/janus-adapter/src/adapters/JanusAdapter.js

This PR includes the `NAF.adapters.register()` API, but does not yet split out the existing adapters into separate modules. I made each of the adapters ready to be split out into their own modules by removing the INetworkAdapter class and other references to networked-aframe. All adapters now reference networked-aframe through the NAF global. The next steps to breaking out these adapters would be to remove them from the AdapterFactory, update the build scripts, and bump the major version.

In this PR there should be no breaking changes to existing apps. Although, the basic-uws.html and deepstream-basic.html examples were broken on master for me and I couldn't test them. I tested all of the other examples successfully.

### CODE REVIEW

**Comment by haydenjameslee** [comment]
Sounds great and makes total sense. Its probably worth finishing the remaining tasks before merging right?

**Comment by robertlong** [comment]
If you merge right now, there will be no breaking changes. The remaining work would split out all of the adapters into separate bundles which would need to be included separately. It's a super simple yet breaking change. Depends how strict you are being with your versioning.

I'm finishing up the JanusAdapter which utilizes this API and want to make sure the NetworkAdapter interface is solid before merging. Once that is done I can make the changes I suggested. Whether that work happens in this PR or a separate PR is up to you.

**Comment by robertlong** [comment]
I've gone ahead and removed the adapters from the AdapterFactory. Now I'm trying to decide what is the best way to build and distribute the adapters. I have 3 possible options I'm looking into and would like some feedback.

1. Keep all of the existing adapters in the current repository. Output the built bundles in `/dist/adapters`.
    Requiring via script tag becomes:
    ```
    <script src="https://unpkg.com/networked-aframe/dist/adapters/naf-easyrtc-adapter.min.js"></script>
    ```
    Via NPM:
    ```
    require("networked-aframe/dist/adapters/naf-easyrtc-adapter");
    ```

2. Split the adapters into separate repositories. Ex. `naf-easyrtc-adapter`. 

3. Use a mono repository via Lerna or Yarn. This is a little more complex, but I think better for things that are dependent on one another. Networked AFrame physics could be broken out into its own package as well.

    Yarn also seems to have made this a bit easier with their workspaces feature:
    https://yarnpkg.com/blog/2017/08/02/introducing-workspaces/

I'm also fine with landing just the first commit of this PR now and taking our time to figure out how to split everything up. It could be a big reorganization of the project and deserves some thought.

**Comment by haydenjameslee** [comment]
I'd like to keep the easyrtc adapter in the library source just for convenience. To store others I'd vote for #2 over #3 just due to familiarity. I think it makes sense to store in different repos that can be updated indpendentently. We may run into issues syncing the version numbers of adapters with NAF if we ever change the NAF adapter interface, however I don't foresee that happening very often.

**Comment by haydenjameslee** [comment]
Maybe unrelated to this PR but as far as adapter interface changes go, I think it makes sense to add the `webrtc` bool back into the `networked-scene` component. Since all adapters that support webrtc signalling will necessarily have a means of transferring data by non-webrtc APIs during the signalling process, they should also be able to do "websocket only" and therefore you should be able to choose webrtc or not with every adapter (or at least every adapter that supports webrtc, some may be websocket only).

Ie. We get rid of the separate `wsEasyRTC` adapter and only have the `easyrtc` adapter, then specifiying webrtc = true / false in `networked-scene` will decide webrtc or not.

**Comment by robertlong** [comment]
Cool, I'll split those adapters out then and move their examples to the separate repositories. [naf-janus-adapter](https://github.com/robertlong/naf-janus-adapter) can be used as a template. I'll leave the `EasyRTCAdapter` in the project as the default.

Let's discuss the second comment in another PR. We don't currently have any plans to send non-signaling data over websockets in the JanusAdapter. Instead we are going to be using reliable datachannels to send that data. WebRTC is currently a requirement, but that may change.

**Comment by netpro2k** [comment]
Rather than having a `webrtc` option I think it would be better to just have a general way of passing arguments to an adapter, every adapters options or going to be different so it doesn't make sense to try and bring them all up to the top level. Questionable if this means `audio` should also get made into an adapter argument (I can see arguments either way)

**Comment by robertlong** [comment]
Ok, I've finished splitting out all of the adapters in to separate repositories. I created a separate organization where these can live and invited you. As soon as you accept I can make you an owner and you can decide whether you want to move the core library over as well.

https://github.com/networked-aframe
https://github.com/networked-aframe/naf-uws-adapter
https://github.com/networked-aframe/naf-firebase-adapter
https://github.com/networked-aframe/naf-deepstream-adapter

Some changes I've made:

Build System (This is what I used for [naf-janus-adapter](https://github.com/robertlong/naf-janus-adapter) and just copied everything over, feel free to keep or change whatever you want):
* upgraded to webpack 3
* setup webpack with webpack-dev-server and webpack-dev-middleware where useful.
* added a Prettier .eslintrc
* used the `babel-preset-env` instead of babel-preset-es2015`
* used `babel-minify-webpack-plugin` instead of uglifyjs through browserify.

Documentation:
* Added heroku deploy button to the uws adapter repo.
* Updated networked-aframe README.md to reference the new repositories.

Fixes:
* Removed lodash as a dependency of firebase-key-encode and fixed a bug in it ([PR](https://github.com/chrisvxd/firebase-key-encode/pull/1)) This removes lodash as a dependency of networked-aframe.

**Comment by haydenjameslee** [comment]
Makes sense to have its own org now that there will be multiple repos. Much better than just referencing them all in the README. I'm happy to move the main repo over too, I'll look into how best to do that.

@netpro2k Agreed some of those `networked-scene` properties have now become adapter specific and we should move to a better system. We can probably do better than the URL query parameter format, but I'm not sure what that would be yet. Definitely the scope of another PR.

@robertlong That Heroku deploy button is awesome! Having similar "Remix on Glitch" buttons would be cool too. The build system sounds good. I don't have much experience configuring JS build systems so can't provide much feedback there.

**Comment by robertlong** [comment]
Yeah. I wanted to do a remix on glitch button for all of them. I’ll try to get that in soon.

**Comment by haydenjameslee** [comment]
Just merged Positional Audio (https://github.com/haydenjameslee/networked-aframe/pull/50) and it caused some conflicts here. It also introduces a new function on the IAdapter interface, getMediaStream (https://github.com/haydenjameslee/networked-aframe/blob/master/src/adapters/INetworkAdapter.js#L22). None of the other adapters support audio yet though so it won't matter.

**Comment by robertlong** [comment]
Fixed the merge conflicts and tested the changes.

**Comment by haydenjameslee** [comment]
Something very odd is happening when I checkout the PR:

image

I've npm prune'd, npm installed and npm updated.

**Comment by robertlong** [comment]
Looks like it was caused by a circular dependency. Should be fixed now.

**Pull request merged**
